import lastmod from '../data/page-lastmod.json';

/**
 * The date a non-article page last changed, so every page type can carry
 * dateModified and not just the collections.
 *
 * The map is generated by scripts/ai-visibility/page-lastmod.mjs from git and
 * committed, because Vercel clones shallow and cannot recompute it.
 */
const map = lastmod as Record<string, string>;

export function lastmodFor(pathnameOrUrl: string | undefined | null): string | null {
  // Layouts across this network resolve the canonical URL in different places, and on
  // some of them the prop itself is optional. A missing value is a missing date, not a
  // build failure.
  if (typeof pathnameOrUrl !== 'string' || !pathnameOrUrl) return null;
  let pathname = pathnameOrUrl;
  try {
    if (/^https?:\/\//.test(pathnameOrUrl)) pathname = new URL(pathnameOrUrl).pathname;
  } catch {
    /* fall through with the raw value */
  }
  if (!pathname.startsWith('/')) pathname = `/${pathname}`;
  if (!pathname.endsWith('/')) pathname = `${pathname}/`;
  if (map[pathname]) return map[pathname];
  // Pages built by a dynamic route share that route's date under a wildcard key. Walk
  // up, because a route can generate more than one path segment: /thailand/pattaya/
  // condos-for-sale/ is produced by src/pages/thailand/[...slug].astro, whose key is
  // /thailand/*.
  const segments = pathname.split('/').filter(Boolean);
  for (let i = segments.length - 1; i >= 0; i -= 1) {
    const prefix = segments.slice(0, i).join('/');
    const key = prefix ? `/${prefix}/*` : '/*';
    if (map[key]) return map[key];
  }
  return null;
}
