/**
 * Search terms used to source one unique Commons image per page.
 * Terms are tried in order; the first that yields an unused, correctly-licensed
 * file at >=1600px wins. Places are named in Portuguese where that returns better
 * Commons coverage.
 */
export const QUERIES = {
  "aimi-wealth-tax-portugal-property": { collection: "guides", terms: ["Cascais villa", "Estoril mansion Portugal", "Quinta do Lago villa"], alt: "Prime Portuguese villa \u2014 AIMI wealth tax applies above \u20ac600,000 of taxable value" },
  "al-license-transfer-portugal-sale": { collection: "guides", terms: ["Lisbon apartment building facade", "Lisboa pr\u00e9dio fachada"], alt: "Lisbon apartment building \u2014 AL licence transfer on sale" },
  "algarve-airbnb-investment-guide": { collection: "guides", terms: ["Algarve holiday apartment", "Algarve resort pool"], alt: "Algarve holiday letting stock \u2014 Airbnb and Alojamento Local investment" },
  "algarve-property-investment-guide": { collection: "guides", terms: ["Algarve coast cliffs", "Praia da Marinha Algarve"], alt: "Algarve coastline \u2014 regional property investment guide" },
  "alojamento-local-license-portugal": { collection: "guides", terms: ["Lisbon azulejo facade", "azulejo Lisboa building"], alt: "Azulejo-tiled Lisbon facade \u2014 Alojamento Local licensing" },
  "best-portugal-property-under-4000-euro-m2": { collection: "guides", terms: ["Portugal residential street town", "Portuguese town houses street"], alt: "Portuguese residential street \u2014 value bands under \u20ac4,000 per square metre" },
  "best-regions-invest-portugal-property-2026": { collection: "guides", terms: ["Portugal aerial landscape coast", "Portugal countryside aerial"], alt: "Portugal from the air \u2014 regional investment comparison" },
  "buy-property-portugal-foreigner": { collection: "guides", terms: ["Lisbon Baixa street", "Rua Augusta Lisboa"], alt: "Lisbon Baixa \u2014 buying property in Portugal as a foreigner" },
  "can-foreigners-buy-property-portugal": { collection: "guides", terms: ["Porto Ribeira houses", "Ribeira Porto colourful"], alt: "Porto Ribeira \u2014 foreign ownership rules in Portugal" },
  "complete-before-september-2026-imt-guide": { collection: "guides", terms: ["Terreiro do Paco Lisbon", "Praca do Comercio Lisboa"], alt: "Terreiro do Pa\u00e7o, Lisbon \u2014 completing before the September 2026 IMT change" },
  "cost-of-buying-property-portugal": { collection: "guides", terms: ["Lisbon Pombaline architecture", "Lisboa Pombalino building"], alt: "Pombaline Lisbon architecture \u2014 full cost of buying Portuguese property" },
  "cpcv-promissory-contract-portugal": { collection: "guides", terms: ["Porto Sao Bento station", "Sao Bento railway station azulejos"], alt: "S\u00e3o Bento, Porto \u2014 CPCV promissory contract stage" },
  "due-diligence-portugal-property": { collection: "guides", terms: ["Coimbra university building", "Universidade de Coimbra"], alt: "Coimbra \u2014 due diligence on Portuguese property" },
  "escritura-notary-portugal-property": { collection: "guides", terms: ["Lisbon city hall", "Camara Municipal de Lisboa"], alt: "Lisbon city hall \u2014 escritura and notary completion" },
  "gross-vs-net-yield-portugal": { collection: "guides", terms: ["Porto apartment buildings", "Porto residential block"], alt: "Porto residential stock \u2014 gross versus net rental yield" },
  "hidden-costs-buying-property-portugal": { collection: "guides", terms: ["Lisbon Alfama alley", "Alfama Lisboa street"], alt: "Alfama, Lisbon \u2014 hidden costs when buying" },
  "highest-rental-yield-areas-portugal": { collection: "guides", terms: ["Braga historic centre", "Braga Portugal square"], alt: "Braga \u2014 among the highest rental yield markets in Portugal" },
  "how-to-buy-portugal-property-remotely": { collection: "guides", terms: ["Lisbon Belem tower", "Torre de Belem"], alt: "Bel\u00e9m, Lisbon \u2014 buying Portuguese property remotely" },
  "how-to-buy-property-portugal-step-by-step": { collection: "guides", terms: ["Lisbon tram 28", "elctrico Lisboa tram"], alt: "Lisbon tram \u2014 the step-by-step purchase process" },
  "how-to-calculate-rental-yield-portugal": { collection: "guides", terms: ["Lisbon rooftops view", "Lisboa telhados miradouro"], alt: "Lisbon rooftops \u2014 calculating rental yield" },
  "imi-property-tax-portugal": { collection: "guides", terms: ["Portugal municipal building camara", "camara municipal Portugal"], alt: "Portuguese municipal building \u2014 IMI is a municipal property tax" },
  "imt-refund-tax-resident-portugal": { collection: "guides", terms: ["Lisbon Avenida da Liberdade", "Avenida da Liberdade Lisboa"], alt: "Avenida da Liberdade, Lisbon \u2014 IMT refund for new tax residents" },
  "imt-tax-non-resident-portugal-2026": { collection: "guides", terms: ["Lisbon skyline aerial", "Lisboa panorama city"], alt: "Lisbon \u2014 flat 7.5% IMT for non-resident buyers from September 2026" },
  "is-portugal-property-good-investment-2026": { collection: "guides", terms: ["Porto Dom Luis bridge", "Ponte Luis I Porto"], alt: "Dom Lu\u00eds I bridge, Porto \u2014 is Portuguese property a good investment" },
  "lisbon-alojamento-local-containment-zones": { collection: "guides", terms: ["Bairro Alto Lisbon", "Bairro Alto Lisboa street"], alt: "Bairro Alto \u2014 Lisbon Alojamento Local containment zones" },
  "lisbon-property-investment-guide": { collection: "guides", terms: ["Lisbon Miradouro view", "Lisboa miradouro Senhora do Monte"], alt: "Lisbon from a miradouro \u2014 city property investment guide" },
  "long-term-vs-holiday-rental-portugal": { collection: "guides", terms: ["Algarve beach town Portugal", "Carvoeiro Algarve"], alt: "Algarve beach town \u2014 long-term versus holiday letting" },
  "moderate-rent-tax-incentives-portugal-2026": { collection: "guides", terms: ["Portugal social housing building", "Portugal modern apartment block"], alt: "Portuguese apartment stock \u2014 moderate-rent tax incentives" },
  "nif-portugal-property-purchase": { collection: "guides", terms: ["Portugal Financas building", "Portugal government building Lisbon"], alt: "Portuguese tax office \u2014 obtaining a NIF" },
  "non-resident-mortgage-portugal": { collection: "guides", terms: ["Lisbon bank building", "Banco de Portugal building"], alt: "Portuguese banking \u2014 non-resident mortgages" },
  "non-resident-rental-income-tax-portugal": { collection: "guides", terms: ["Porto street houses", "Porto Cedofeita street"], alt: "Porto letting stock \u2014 non-resident rental income tax" },
  "off-plan-property-portugal-guide": { collection: "guides", terms: ["Portugal construction site building", "Lisbon construction crane"], alt: "Portuguese construction \u2014 off-plan purchase guide" },
  "porto-alojamento-local-rules": { collection: "guides", terms: ["Porto historic centre UNESCO", "Porto Clerigos tower"], alt: "Porto historic centre \u2014 Alojamento Local rules" },
  "porto-property-investment-guide": { collection: "guides", terms: ["Porto Douro riverside", "Porto Douro river view"], alt: "Porto and the Douro \u2014 city investment guide" },
  "portugal-buy-to-let-investment-guide": { collection: "guides", terms: ["Lisbon Graca neighbourhood", "Graca Lisboa street"], alt: "Gra\u00e7a, Lisbon \u2014 buy-to-let investment" },
  "portugal-buying-costs-calculator-examples": { collection: "guides", terms: ["Portugal apartment interior", "Portuguese apartment living room"], alt: "Portuguese apartment \u2014 worked buying cost examples" },
  "portugal-capital-gains-tax-property": { collection: "guides", terms: ["Cascais marina Portugal", "Cascais bay Portugal"], alt: "Cascais \u2014 capital gains on Portuguese property sales" },
  "portugal-d7-visa-property": { collection: "guides", terms: ["Tavira Algarve town", "Tavira Portugal bridge"], alt: "Tavira \u2014 the D7 passive income visa" },
  "portugal-digital-nomad-visa-property": { collection: "guides", terms: ["Lisbon LX Factory", "Lisboa coworking creative"], alt: "Lisbon creative quarter \u2014 the D8 digital nomad visa" },
  "portugal-golden-visa-fund-investment-2026": { collection: "guides", terms: ["Lisbon Parque Eduardo VII", "Parque Eduardo VII Lisboa"], alt: "Lisbon \u2014 Golden Visa fund route" },
  "portugal-golden-visa-real-estate-ended": { collection: "guides", terms: ["Lisbon Praca Marques de Pombal", "Marques de Pombal Lisboa"], alt: "Lisbon \u2014 the Golden Visa real estate route ended in 2023" },
  "portugal-golden-visa-vs-property-purchase": { collection: "guides", terms: ["Lisbon Amoreiras towers", "Lisboa modern towers"], alt: "Lisbon \u2014 Golden Visa versus a direct property purchase" },
  "portugal-housing-supply-licensing-2025": { collection: "guides", terms: ["Portugal new housing development", "Portugal residential development new"], alt: "New Portuguese housing supply and licensing" },
  "portugal-mortgage-rates-foreigners-2026": { collection: "guides", terms: ["Porto Avenida dos Aliados", "Aliados Porto avenue"], alt: "Porto \u2014 mortgage rates for foreign buyers" },
  "portugal-property-1-million-plus-investment": { collection: "guides", terms: ["Comporta beach Portugal", "Melides Alentejo coast"], alt: "The Alentejo coast \u2014 the \u20ac1M-plus market" },
  "portugal-property-deposit-guide-cpcv": { collection: "guides", terms: ["Portugal house keys door", "Portuguese front door traditional"], alt: "A Portuguese doorway \u2014 CPCV deposit stage" },
  "portugal-property-developers-guide-2026": { collection: "guides", terms: ["Lisbon modern architecture building", "Lisboa arquitetura contemporanea"], alt: "Contemporary Lisbon architecture \u2014 Portuguese developers" },
  "portugal-property-inheritance-tax-foreigners": { collection: "guides", terms: ["Sintra Pena palace", "Palacio da Pena Sintra"], alt: "Sintra \u2014 inheritance and succession for foreign owners" },
  "portugal-property-investment-guide": { collection: "guides", terms: ["Portugal coastline aerial view", "Portugal Atlantic coast"], alt: "The Portuguese coast \u2014 national investment guide" },
  "portugal-property-market-forecast-2026-2027": { collection: "guides", terms: ["Lisbon Parque das Nacoes modern", "Parque das Nacoes Lisboa architecture"], alt: "Parque das Na\u00e7\u00f5es \u2014 market forecast to 2027" },
  "portugal-property-market-record-2025-ine-data": { collection: "guides", terms: ["Porto panorama city view", "Porto skyline Portugal"], alt: "Porto \u2014 record 2025 transaction data" },
  "portugal-property-scams-avoid": { collection: "guides", terms: ["Portugal abandoned house ruin", "Portuguese derelict building"], alt: "A derelict Portuguese property \u2014 avoiding scams" },
  "portugal-property-under-300000-euros": { collection: "guides", terms: ["Silver Coast Portugal town", "Peniche Portugal town"], alt: "Silver Coast town \u2014 property under \u20ac300,000" },
  "portugal-property-under-500000-euros": { collection: "guides", terms: ["Matosinhos Porto seaside", "Foz do Douro Porto"], alt: "Porto seaside \u2014 property under \u20ac500,000" },
  "portugal-rental-yield-guide": { collection: "guides", terms: ["Lisbon Estrela basilica neighbourhood", "Estrela Lisboa"], alt: "Estrela, Lisbon \u2014 national rental yield guide" },
  "portugal-residency-options-without-golden-visa": { collection: "guides", terms: ["Portugal Douro valley vineyards", "Douro valley terraces"], alt: "The Douro valley \u2014 residency routes after the Golden Visa" },
  "power-of-attorney-property-portugal": { collection: "guides", terms: ["Portugal consulate embassy building", "Portuguese historic government building"], alt: "Power of attorney for a Portuguese purchase" },
  "prenuptial-agreement-portugal-property": { collection: "guides", terms: ["Portugal church wedding traditional", "Portuguese chapel countryside"], alt: "Marriage property regimes in Portugal" },
  "property-maintenance-costs-portugal": { collection: "guides", terms: ["Portugal building renovation scaffolding", "Lisbon building restoration"], alt: "Portuguese building maintenance and renovation" },
  "property-management-portugal-cost": { collection: "guides", terms: ["Algarve apartment complex", "Vilamoura apartments Algarve"], alt: "Algarve apartment complex \u2014 property management costs" },
  "rnal-registration-portugal": { collection: "guides", terms: ["Lisbon guesthouse balcony", "Portuguese balcony flowers apartment"], alt: "Portuguese short-let accommodation \u2014 RNAL registration" },
  "silver-coast-portugal-property-guide": { collection: "guides", terms: ["Nazare Portugal cliff", "Sao Martinho do Porto bay"], alt: "The Silver Coast \u2014 regional property guide" },
  "stamp-duty-portugal-property": { collection: "guides", terms: ["Portugal historic archive building", "Portuguese national archive"], alt: "Portuguese stamp duty on property transfers" },
  "albufeira-property-investment": { collection: "areas", terms: ["Albufeira Algarve", "Albufeira beach Portugal"], alt: "Albufeira, Algarve" },
  "alcantara-property-investment": { collection: "areas", terms: ["Alcantara Lisbon", "Alcantara Lisboa district"], alt: "Alc\u00e2ntara, Lisbon" },
  "aveiro-property-investment": { collection: "areas", terms: ["Aveiro Portugal canal", "Aveiro moliceiro"], alt: "Aveiro and its canals" },
  "braga-property-investment": { collection: "areas", terms: ["Braga Portugal", "Bom Jesus Braga"], alt: "Braga, Norte" },
  "caldas-da-rainha-property-investment": { collection: "areas", terms: ["Caldas da Rainha", "Caldas da Rainha Portugal park"], alt: "Caldas da Rainha, Silver Coast" },
  "cascais-property-investment": { collection: "areas", terms: ["Cascais Portugal", "Cascais bay marina"], alt: "Cascais" },
  "chiado-principe-real-property": { collection: "areas", terms: ["Chiado Lisbon", "Principe Real Lisboa"], alt: "Chiado and Pr\u00edncipe Real, Lisbon" },
  "coimbra-property-investment": { collection: "areas", terms: ["Coimbra Portugal", "Coimbra Mondego river"], alt: "Coimbra" },
  "comporta-property-investment": { collection: "areas", terms: ["Comporta Portugal", "Comporta beach Alentejo"], alt: "Comporta" },
  "ericeira-property-investment": { collection: "areas", terms: ["Ericeira Portugal", "Ericeira surf coast"], alt: "Ericeira" },
  "faro-property-investment": { collection: "areas", terms: ["Faro Portugal", "Faro Algarve old town"], alt: "Faro, Algarve" },
  "lagos-property-investment": { collection: "areas", terms: ["Lagos Algarve Portugal", "Ponta da Piedade Lagos"], alt: "Lagos, western Algarve" },
  "lourinha-property-investment": { collection: "areas", terms: ["Lourinha Portugal", "Lourinha beach"], alt: "Lourinh\u00e3, Silver Coast" },
  "madeira-property-investment-guide": { collection: "areas", terms: ["Funchal Madeira", "Madeira island Funchal bay"], alt: "Funchal, Madeira" },
  "marvila-property-investment": { collection: "areas", terms: ["Marvila Lisbon", "Marvila Lisboa"], alt: "Marvila, Lisbon" },
  "matosinhos-property-investment": { collection: "areas", terms: ["Matosinhos Portugal", "Matosinhos beach Porto"], alt: "Matosinhos" },
  "nazare-property-investment": { collection: "areas", terms: ["Nazare Portugal", "Nazare beach cliff"], alt: "Nazar\u00e9" },
  "obidos-property-investment": { collection: "areas", terms: ["Obidos Portugal", "Obidos castle walls"], alt: "\u00d3bidos" },
  "oeiras-property-investment": { collection: "areas", terms: ["Oeiras Portugal", "Oeiras coast Lisbon"], alt: "Oeiras" },
  "parque-das-nacoes-property": { collection: "areas", terms: ["Parque das Nacoes Lisbon", "Oriente Lisboa"], alt: "Parque das Na\u00e7\u00f5es, Lisbon" },
  "portimao-property-investment": { collection: "areas", terms: ["Portimao Algarve", "Praia da Rocha Portimao"], alt: "Portim\u00e3o, Algarve" },
  "setubal-peninsula-property-investment": { collection: "areas", terms: ["Setubal Portugal", "Arrabida Setubal"], alt: "The Set\u00fabal peninsula" },
  "sintra-property-investment": { collection: "areas", terms: ["Sintra Portugal", "Sintra palace hills"], alt: "Sintra" },
  "tavira-property-investment": { collection: "areas", terms: ["Tavira Algarve", "Tavira Portugal old town"], alt: "Tavira, eastern Algarve" },
  "vila-nova-de-gaia-property-investment": { collection: "areas", terms: ["Vila Nova de Gaia", "Gaia port cellars Douro"], alt: "Vila Nova de Gaia" },
  "vilamoura-property-investment": { collection: "areas", terms: ["Vilamoura Algarve", "Vilamoura marina"], alt: "Vilamoura" },
  "algarve-vs-lisbon-property-investment": { collection: "compare", terms: ["Algarve marina boats", "Lagoa Algarve coast"], alt: "Algarve versus Lisbon" },
  "lagos-vs-vilamoura-investment": { collection: "compare", terms: ["Algarve golf course Portugal", "Quinta do Lago golf"], alt: "Lagos versus Vilamoura" },
  "lisbon-vs-cascais-property": { collection: "compare", terms: ["Estoril coast Portugal", "Cascais Estoril seafront"], alt: "Lisbon versus Cascais" },
  "new-build-vs-resale-property-portugal": { collection: "compare", terms: ["Portugal new apartment building modern", "Lisbon new residential building"], alt: "New-build versus resale in Portugal" },
  "porto-vs-lisbon-property-investment": { collection: "compare", terms: ["Porto Vila Nova de Gaia panorama", "Porto Douro bridges"], alt: "Porto versus Lisbon" },
  "portugal-vs-cyprus-property-investment": { collection: "compare", terms: ["Algarve white houses village", "Algarve traditional chimney"], alt: "Portugal versus Cyprus" },
  "portugal-vs-dubai-property-investment": { collection: "compare", terms: ["Lisbon business district", "Lisboa Avenidas Novas"], alt: "Portugal versus Dubai" },
  "portugal-vs-france-property-investment": { collection: "compare", terms: ["Portugal vineyard Alentejo", "Alentejo landscape Portugal"], alt: "Portugal versus France" },
  "portugal-vs-greece-property-investment": { collection: "compare", terms: ["Portugal fishing village coast", "Portuguese coastal village"], alt: "Portugal versus Greece" },
  "portugal-vs-italy-property-investment": { collection: "compare", terms: ["Porto azulejo church", "Portuguese tiled church facade"], alt: "Portugal versus Italy" },
  "portugal-vs-malta-property-investment": { collection: "compare", terms: ["Madeira coast cliffs", "Madeira Ponta de Sao Lourenco"], alt: "Portugal versus Malta" },
  "portugal-vs-spain-property-investment": { collection: "compare", terms: ["Portugal Spain border river Guadiana", "Guadiana river bridge Portugal"], alt: "Portugal versus Spain" },
  "portugal-vs-turkey-property-investment": { collection: "compare", terms: ["Portugal castle hilltop", "Portuguese medieval castle"], alt: "Portugal versus Turkey" },
  "portugal-vs-uk-property-investment": { collection: "compare", terms: ["Portugal Atlantic beach surf", "Portuguese Atlantic coastline"], alt: "Portugal versus the UK" },
  "american-buyers-portugal-property": { collection: "segments", terms: ["Lisbon Cais do Sodre", "Cais do Sodre Lisboa"], alt: "Lisbon \u2014 guidance for American buyers" },
  "angolan-buyers-portugal": { collection: "segments", terms: ["Lisbon multicultural street market", "Lisboa mercado"], alt: "Lisbon \u2014 guidance for Angolan buyers" },
  "australian-buyers-portugal-property": { collection: "segments", terms: ["Ericeira surf beach Portugal", "Peniche surf Portugal"], alt: "The Portuguese surf coast \u2014 guidance for Australian buyers" },
  "brazilian-buyers-portugal-property": { collection: "segments", terms: ["Lisbon Praca do Rossio", "Rossio Lisboa square"], alt: "Rossio, Lisbon \u2014 guidance for Brazilian buyers" },
  "canadian-buyers-portugal-property": { collection: "segments", terms: ["Porto riverside houses", "Porto Miragaia"], alt: "Porto \u2014 guidance for Canadian buyers" },
  "chinese-buyers-portugal-property": { collection: "segments", terms: ["Lisbon Avenida shops", "Lisboa Chiado shopping street"], alt: "Lisbon \u2014 guidance for Chinese buyers" },
  "french-buyers-portugal-property": { collection: "segments", terms: ["Algarve village square Portugal", "Loule Algarve"], alt: "The Algarve \u2014 guidance for French buyers" },
  "german-buyers-portugal-property": { collection: "segments", terms: ["Algarve countryside Portugal", "Monchique Algarve hills"], alt: "The Algarve interior \u2014 guidance for German buyers" },
  "indian-buyers-portugal-property": { collection: "segments", terms: ["Lisbon Alcantara docks", "Doca de Alcantara Lisboa"], alt: "Lisbon docks \u2014 guidance for Indian buyers" },
  "israeli-buyers-portugal-property": { collection: "segments", terms: ["Porto synagogue historic Portugal", "Porto historic quarter"], alt: "Porto \u2014 guidance for Israeli buyers" },
  "south-african-buyers-portugal-property": { collection: "segments", terms: ["Algarve seafront promenade", "Albufeira marina Algarve"], alt: "The Algarve \u2014 guidance for South African buyers" },
  "uae-buyers-portugal-property": { collection: "segments", terms: ["Lisbon luxury waterfront", "Lisboa Belem waterfront"], alt: "Lisbon waterfront \u2014 guidance for UAE buyers" },
  "uk-buyers-portugal-property-brexit": { collection: "segments", terms: ["Algarve golf resort Portugal", "Vale do Lobo Algarve"], alt: "The Algarve \u2014 guidance for UK buyers after Brexit" },
  "carvalhido": { collection: "projects", terms: ["Porto Carvalhido", "Porto Paranhos street"], alt: "Carvalhido, Porto" },
  "castilho-203": { collection: "projects", terms: ["Lisbon Avenidas Novas building", "Rua Castilho Lisboa"], alt: "Avenidas Novas, Lisbon" },
  "infinity": { collection: "projects", terms: ["Sete Rios Lisbon", "Lisboa Sete Rios"], alt: "Sete Rios, Lisbon" },
  "mar-adentro": { collection: "projects", terms: ["Faro Algarve marina", "Faro waterfront Portugal"], alt: "Faro, Algarve" },
  "six-senses-comporta": { collection: "projects", terms: ["Comporta rice fields", "Comporta Alentejo pine"], alt: "Comporta, Alentejo" },
  "terracos-do-monte": { collection: "projects", terms: ["Graca Lisbon viewpoint", "Lisboa Graca miradouro"], alt: "Gra\u00e7a, Lisbon" },
  "tomas-ribeiro-79": { collection: "projects", terms: ["Avenidas Novas Lisboa street", "Saldanha Lisboa"], alt: "Avenidas Novas, Lisbon" },
  "farinvest-properties-portugal": { collection: "developers", terms: ["Lisbon estate agency street", "Lisboa commercial street"], alt: "Lisbon \u2014 brokerage due diligence" },
  "vanguard-properties-portugal": { collection: "developers", terms: ["Lisbon contemporary residential architecture", "Lisboa novo edificio residencial"], alt: "Contemporary Lisbon development" },
  "vic-properties-portugal": { collection: "developers", terms: ["Lisbon Matinha waterfront", "Lisboa Braco de Prata"], alt: "Lisbon riverfront regeneration" },
};
